-- P1-A：AI 出题批次、题目草稿与来源追溯表
-- 题目范围支持小节或章节，视频测验默认以小节为范围

CREATE TABLE IF NOT EXISTS `ai_question_batch` (
  `id` BIGINT NOT NULL COMMENT 'AI 出题批次 ID',
  `course_id` BIGINT NOT NULL COMMENT '课程 ID',
  `course_name` VARCHAR(255) NOT NULL COMMENT '课程名称',
  `scope_type` VARCHAR(32) NOT NULL COMMENT '出题范围：SECTION 或 CHAPTER',
  `scope_id` BIGINT NOT NULL COMMENT '出题范围目录 ID',
  `scope_name` VARCHAR(255) NOT NULL COMMENT '出题范围名称',
  `scope_section_ids` JSON DEFAULT NULL COMMENT '章级出题选择的小节 ID 列表',
  `scope_section_names` JSON DEFAULT NULL COMMENT '章级出题选择的小节名称列表',
  `source_type` VARCHAR(32) NOT NULL COMMENT '素材来源：MANUAL_TOPIC、MATERIAL_TEXT、VIDEO_TRANSCRIPT、VIDEO_SUMMARY',
  `source_id` VARCHAR(128) DEFAULT NULL COMMENT '素材来源 ID',
  `source_version` VARCHAR(128) DEFAULT NULL COMMENT '素材来源版本',
  `target_biz_id` BIGINT NOT NULL COMMENT '目标练习目录 ID',
  `knowledge_points` JSON DEFAULT NULL COMMENT '知识点列表',
  `material_text` LONGTEXT COMMENT '出题素材文本',
  `question_types` JSON NOT NULL COMMENT '题型列表',
  `question_count` INT NOT NULL COMMENT '题目数量',
  `difficulty` TINYINT NOT NULL COMMENT '难度：1 简单、2 中等、3 困难',
  `score` INT NOT NULL COMMENT '单题分值',
  `cate_id1` BIGINT NOT NULL COMMENT '一级分类 ID',
  `cate_id2` BIGINT NOT NULL COMMENT '二级分类 ID',
  `cate_id3` BIGINT NOT NULL COMMENT '三级分类 ID',
  `status` VARCHAR(32) NOT NULL COMMENT '批次状态',
  `total_count` INT NOT NULL DEFAULT 0 COMMENT '题目总数',
  `valid_count` INT NOT NULL DEFAULT 0 COMMENT '有效题目数',
  `duplicate_count` INT NOT NULL DEFAULT 0 COMMENT '重复题目数',
  `published_count` INT NOT NULL DEFAULT 0 COMMENT '已发布题目数',
  `failure_reason` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '幂等请求 ID',
  `request_fingerprint` CHAR(64) NOT NULL COMMENT '请求指纹 SHA-256',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `creater` BIGINT NOT NULL,
  `updater` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_question_batch_creator_request` (`creater`, `request_id`),
  KEY `idx_ai_question_batch_creator_status` (`creater`, `status`),
  KEY `idx_ai_question_batch_course_scope` (`course_id`, `scope_type`, `scope_id`),
  KEY `idx_ai_question_batch_target` (`target_biz_id`),
  KEY `idx_ai_question_batch_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 出题批次';

CREATE TABLE IF NOT EXISTS `ai_question_draft` (
  `id` BIGINT NOT NULL COMMENT 'AI 题目草稿 ID',
  `batch_id` BIGINT NOT NULL COMMENT 'AI 出题批次 ID',
  `sequence_no` INT NOT NULL COMMENT '题目顺序号',
  `name` VARCHAR(1000) DEFAULT NULL COMMENT '题干',
  `type` TINYINT DEFAULT NULL COMMENT '题型：1 单选、2 多选、3 不定项选择、4 判断、5 主观',
  `difficulty` TINYINT DEFAULT NULL COMMENT '难度：1 简单、2 中等、3 困难',
  `score` INT DEFAULT NULL COMMENT '题目分值',
  `options` JSON DEFAULT NULL COMMENT '选项列表',
  `answer` LONGTEXT COMMENT '参考答案',
  `analysis` LONGTEXT COMMENT '题目解析',
  `knowledge_points` JSON DEFAULT NULL COMMENT '关联知识点',
  `content_fingerprint` CHAR(64) DEFAULT NULL COMMENT '题目内容指纹',
  `status` VARCHAR(32) NOT NULL COMMENT '草稿状态',
  `validation_message` VARCHAR(1000) DEFAULT NULL COMMENT '校验信息',
  `question_id` BIGINT DEFAULT NULL COMMENT '正式题目 ID',
  `confirmed_by` BIGINT DEFAULT NULL COMMENT '确认人 ID',
  `confirmed_time` DATETIME DEFAULT NULL COMMENT '确认时间',
  `published_time` DATETIME DEFAULT NULL COMMENT '发布时间',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `creater` BIGINT NOT NULL,
  `updater` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_question_draft_batch_sequence` (`batch_id`, `sequence_no`),
  KEY `idx_ai_question_draft_batch_status` (`batch_id`, `status`),
  KEY `idx_ai_question_draft_fingerprint` (`content_fingerprint`),
  KEY `idx_ai_question_draft_question` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 题目草稿';

CREATE TABLE IF NOT EXISTS `ai_question_origin` (
  `id` BIGINT NOT NULL COMMENT 'AI 题目来源 ID',
  `question_id` BIGINT NOT NULL COMMENT '正式题目 ID',
  `batch_id` BIGINT NOT NULL COMMENT 'AI 出题批次 ID',
  `draft_id` BIGINT NOT NULL COMMENT 'AI 题目草稿 ID',
  `course_id` BIGINT NOT NULL COMMENT '课程 ID',
  `scope_type` VARCHAR(32) NOT NULL COMMENT '出题范围类型',
  `scope_id` BIGINT NOT NULL COMMENT '出题范围目录 ID',
  `source_type` VARCHAR(32) NOT NULL COMMENT '素材来源类型',
  `source_id` VARCHAR(128) DEFAULT NULL COMMENT '素材来源 ID',
  `source_version` VARCHAR(128) DEFAULT NULL COMMENT '素材来源版本',
  `target_biz_id` BIGINT NOT NULL COMMENT '目标练习目录 ID',
  `content_fingerprint` CHAR(64) DEFAULT NULL COMMENT '题目内容指纹',
  `create_time` DATETIME NOT NULL,
  `creater` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_question_origin_question` (`question_id`),
  UNIQUE KEY `uk_ai_question_origin_draft` (`draft_id`),
  KEY `idx_ai_question_origin_batch` (`batch_id`),
  KEY `idx_ai_question_origin_source` (`source_type`, `source_id`, `source_version`),
  KEY `idx_ai_question_origin_course_scope` (`course_id`, `scope_type`, `scope_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 题目来源追溯';
