-- P1-B/P1-C：学生练习、客观题自动判分、错题闭环和主观题 AI 评估建议。
-- 使用相关接口前，请先在项目考试数据库中手动执行本脚本。

CREATE TABLE IF NOT EXISTS `practice_session` (
  `id` BIGINT NOT NULL COMMENT '练习会话 ID',
  `user_id` BIGINT NOT NULL COMMENT '学生用户 ID',
  `course_id` BIGINT NOT NULL COMMENT '课程 ID',
  `target_biz_id` BIGINT NOT NULL COMMENT '练习目录 ID（目录类型 3）',
  `target_name` VARCHAR(255) NOT NULL COMMENT '练习目录名称快照',
  `status` VARCHAR(32) NOT NULL COMMENT '会话状态',
  `total_questions` INT NOT NULL DEFAULT 0 COMMENT '题目总数',
  `answered_count` INT NOT NULL DEFAULT 0 COMMENT '已作答题目数',
  `objective_count` INT NOT NULL DEFAULT 0 COMMENT '客观题数量',
  `subjective_count` INT NOT NULL DEFAULT 0 COMMENT '主观题数量',
  `total_score` INT NOT NULL DEFAULT 0 COMMENT '练习总分',
  `objective_full_score` INT NOT NULL DEFAULT 0 COMMENT '客观题总分',
  `objective_score` INT NOT NULL DEFAULT 0 COMMENT '客观题实际得分',
  `final_score` INT NOT NULL DEFAULT 0 COMMENT '当前正式总分',
  `correct_count` INT NOT NULL DEFAULT 0 COMMENT '客观题答对数量',
  `ai_review_pending_count` INT NOT NULL DEFAULT 0 COMMENT '待完成 AI 评估、失败重试或人工确认的主观题数量',
  `ai_review_retry_count` INT NOT NULL DEFAULT 0 COMMENT '主观题 AI 评估已重试次数',
  `ai_review_max_retry_count` INT NOT NULL DEFAULT 3 COMMENT '主观题 AI 评估最大重试次数',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '客户端幂等键',
  `submitted_time` DATETIME DEFAULT NULL COMMENT '提交时间',
  `completed_time` DATETIME DEFAULT NULL COMMENT '全部判分完成时间',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_practice_session_user_request` (`user_id`, `request_id`),
  KEY `idx_practice_session_user_status` (`user_id`, `status`),
  KEY `idx_practice_session_user_create` (`user_id`, `create_time`),
  KEY `idx_practice_session_course_target` (`course_id`, `target_biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生练习会话';

CREATE TABLE IF NOT EXISTS `practice_question` (
  `id` BIGINT NOT NULL COMMENT '练习题目快照 ID',
  `session_id` BIGINT NOT NULL COMMENT '练习会话 ID',
  `question_id` BIGINT NOT NULL COMMENT '正式题目 ID',
  `sequence_no` INT NOT NULL COMMENT '会话内题目顺序',
  `name` VARCHAR(1000) NOT NULL COMMENT '题干快照',
  `type` TINYINT NOT NULL COMMENT '1 单选，2 多选，3 不定项，4 判断，5 主观',
  `difficulty` TINYINT NOT NULL COMMENT '题目难度快照',
  `score` INT NOT NULL COMMENT '题目分值快照',
  `options` JSON DEFAULT NULL COMMENT '选项快照',
  `standard_answer` LONGTEXT NOT NULL COMMENT '标准答案快照',
  `analysis` LONGTEXT COMMENT '答案解析快照',
  `grading_method` VARCHAR(32) NOT NULL COMMENT '判分方式：OBJECTIVE_RULE 或 AI_SUGGESTION',
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_practice_question_session_sequence` (`session_id`, `sequence_no`),
  UNIQUE KEY `uk_practice_question_session_question` (`session_id`, `question_id`),
  KEY `idx_practice_question_question` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='练习题目快照';

CREATE TABLE IF NOT EXISTS `practice_answer` (
  `id` BIGINT NOT NULL COMMENT '练习答案 ID',
  `session_id` BIGINT NOT NULL COMMENT '练习会话 ID',
  `practice_question_id` BIGINT NOT NULL COMMENT '练习题目快照 ID',
  `question_id` BIGINT NOT NULL COMMENT '正式题目 ID',
  `user_id` BIGINT NOT NULL COMMENT '学生用户 ID',
  `student_answer` LONGTEXT COMMENT '学生答案',
  `status` VARCHAR(32) NOT NULL COMMENT '答案状态',
  `score` INT DEFAULT NULL COMMENT '规则判分或最终展示分数',
  `correct` TINYINT(1) DEFAULT NULL COMMENT '客观题是否正确',
  `ai_suggested_score` INT DEFAULT NULL COMMENT 'AI 建议分',
  `ai_total_score` INT DEFAULT NULL COMMENT '主观题总分',
  `matched_points` JSON DEFAULT NULL COMMENT '已命中的得分点',
  `missing_points` JSON DEFAULT NULL COMMENT '缺失的得分点',
  `incorrect_statements` JSON DEFAULT NULL COMMENT '存在问题的表述',
  `improvement_suggestion` TEXT COMMENT '改进建议',
  `confidence` DECIMAL(5,4) DEFAULT NULL COMMENT 'AI 评估置信度，取值 0 到 1',
  `manual_review_recommended` TINYINT(1) DEFAULT NULL COMMENT '是否建议人工复核',
  `rubric_version` VARCHAR(64) DEFAULT NULL COMMENT '评分规则版本',
  `ai_failure_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'AI 评估失败原因',
  `answer_time` DATETIME DEFAULT NULL COMMENT '最近作答时间',
  `evaluated_time` DATETIME DEFAULT NULL COMMENT '完成判分或评估时间',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_practice_answer_session_question` (`session_id`, `practice_question_id`),
  KEY `idx_practice_answer_session_status` (`session_id`, `status`),
  KEY `idx_practice_answer_user_question` (`user_id`, `question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生练习答案';

CREATE TABLE IF NOT EXISTS `wrong_question` (
  `id` BIGINT NOT NULL COMMENT '错题记录 ID',
  `user_id` BIGINT NOT NULL COMMENT '学生用户 ID',
  `question_id` BIGINT NOT NULL COMMENT '正式题目 ID',
  `course_id` BIGINT NOT NULL COMMENT '课程 ID',
  `target_biz_id` BIGINT NOT NULL COMMENT '练习目录 ID',
  `latest_practice_question_id` BIGINT NOT NULL COMMENT '最近练习题目快照 ID',
  `latest_answer_id` BIGINT NOT NULL COMMENT '最近错误答案 ID',
  `wrong_count` INT NOT NULL DEFAULT 1 COMMENT '累计答错次数',
  `review_count` INT NOT NULL DEFAULT 0 COMMENT '累计重做次数',
  `status` VARCHAR(32) NOT NULL COMMENT '错题状态：ACTIVE 或 MASTERED',
  `last_wrong_time` DATETIME NOT NULL COMMENT '最近答错时间',
  `last_review_time` DATETIME DEFAULT NULL COMMENT '最近重做时间',
  `mastered_time` DATETIME DEFAULT NULL COMMENT '最近掌握时间',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wrong_question_scope` (`user_id`, `course_id`, `target_biz_id`, `question_id`),
  KEY `idx_wrong_question_user_status` (`user_id`, `status`),
  KEY `idx_wrong_question_user_course` (`user_id`, `course_id`),
  KEY `idx_wrong_question_latest_snapshot` (`latest_practice_question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生错题记录';

CREATE TABLE IF NOT EXISTS `wrong_question_review` (
  `id` BIGINT NOT NULL COMMENT '错题重做记录 ID',
  `wrong_question_id` BIGINT NOT NULL COMMENT '错题记录 ID',
  `user_id` BIGINT NOT NULL COMMENT '学生用户 ID',
  `student_answer` LONGTEXT NOT NULL COMMENT '本次重做答案',
  `correct` TINYINT(1) NOT NULL COMMENT '本次重做是否正确',
  `score` INT NOT NULL DEFAULT 0 COMMENT '本次重做得分',
  `review_time` DATETIME NOT NULL COMMENT '重做时间',
  PRIMARY KEY (`id`),
  KEY `idx_wrong_question_review_wrong_time` (`wrong_question_id`, `review_time`),
  KEY `idx_wrong_question_review_user_time` (`user_id`, `review_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='错题重做记录';