-- 视频 AI 处理任务表
-- 执行前请确认当前连接的数据库为 tj_aigc。

CREATE TABLE IF NOT EXISTS `video_ai_task` (
  `id` BIGINT NOT NULL COMMENT '视频 AI 任务 ID',
  `course_id` BIGINT NOT NULL COMMENT '课程 ID',
  `section_id` BIGINT NOT NULL COMMENT '小节目录 ID',
  `section_name` VARCHAR(255) NOT NULL COMMENT '小节名称快照',
  `media_id` BIGINT NOT NULL COMMENT '媒资 ID',
  `media_name` VARCHAR(255) NOT NULL COMMENT '媒资文件名快照',
  `media_url` VARCHAR(2000) NOT NULL COMMENT '转写时使用的媒资地址快照',
  `media_size` BIGINT NOT NULL COMMENT '媒资大小，单位字节',
  `duration_ms` BIGINT NOT NULL COMMENT '视频时长，单位毫秒',
  `transcription_provider` VARCHAR(64) NOT NULL COMMENT '视频转写 Provider',
  `provider_version` VARCHAR(64) DEFAULT NULL COMMENT 'Provider 版本',
  `config_version` VARCHAR(64) NOT NULL COMMENT '视频 AI 处理配置版本',
  `language` VARCHAR(16) NOT NULL DEFAULT 'zh' COMMENT '识别语言',
  `status` VARCHAR(32) NOT NULL COMMENT '任务状态',
  `progress` TINYINT NOT NULL DEFAULT 0 COMMENT '任务进度，0 到 100',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  `full_text` LONGTEXT COMMENT '视频转写全文',
  `transcript_segments` JSON DEFAULT NULL COMMENT '带时间戳的转写句段',
  `timestamp_mode` VARCHAR(32) DEFAULT NULL COMMENT '时间戳模式：PROVIDER 或 ESTIMATED',
  `video_introduction` TEXT COMMENT '视频简介',
  `core_content` LONGTEXT COMMENT '核心内容',
  `section_summaries` JSON DEFAULT NULL COMMENT '分段摘要',
  `key_conclusions` JSON DEFAULT NULL COMMENT '关键结论',
  `suitable_learners` JSON DEFAULT NULL COMMENT '适合学习者',
  `review_points` JSON DEFAULT NULL COMMENT '建议复习点',
  `knowledge_points` JSON DEFAULT NULL COMMENT '视频知识点',
  `result_version` VARCHAR(64) DEFAULT NULL COMMENT '视频分析结果版本',
  `failure_reason` VARCHAR(1000) DEFAULT NULL COMMENT '失败原因',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '客户端幂等键',
  `started_time` DATETIME DEFAULT NULL COMMENT '首次开始执行时间',
  `transcribed_time` DATETIME DEFAULT NULL COMMENT '转写完成时间',
  `completed_time` DATETIME DEFAULT NULL COMMENT '全部完成时间',
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `creater` BIGINT NOT NULL,
  `updater` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_video_ai_task_creator_request` (`creater`, `request_id`),
  UNIQUE KEY `uk_video_ai_task_creator_media_config` (`creater`, `media_id`, `config_version`),
  KEY `idx_video_ai_task_course_section` (`course_id`, `section_id`),
  KEY `idx_video_ai_task_media` (`media_id`),
  KEY `idx_video_ai_task_creator_status` (`creater`, `status`),
  KEY `idx_video_ai_task_status_update` (`status`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视频 AI 处理任务';